---
vagrant_cloud:
  username: trombik

provider:
  - virtualbox
  - libvirt
box:
  - name: freebsd-11.3-amd64
    version: 20200416
  - name: freebsd-12.1-amd64
    version: 20200416
  - name: ubuntu-16.04-amd64
    version: 20200416
  - name: ubuntu-18.04-amd64
    version: 20200416
  - name: centos-7.4-x86_64
    version: 20200416
  - name: openbsd-6.5-amd64
    version: 20200416
  - name: openbsd-6.6-amd64
    version: 20200416
  - name: openbsd-6.7-amd64
    version: 20200522
